---
- name: "Use python3"
  set_fact: ansible_python_interpreter=/usr/bin/python3

- name: "Create ansible group"
  group:
    name: ansible
    state: present

# ansible % ansible all -i localhost, -m debug -a "msg={{ 'password' | password_hash('sha512', 'mysecretsalt') }}"
# see ansible_user_password in ansible/playbooks/group_vars/all/vault
- name: "Create ansible user"
  user:
    name: ansible
    group: ansible
    password: "{{ ansible_user_encrypted_password }}"
    home: /home/ansible

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
