---
- name: "Use python3"
  set_fact: ansible_python_interpreter=/usr/bin/python3

- name: "Install docker requests"
  pip:
    name: docker, requests
    executable: pip3
  environment:
    http_proxy: "{{ proxy_server }}"
    https_proxy: "{{ proxy_server }}"

- name: "Create docker config directories"
  file:
    path: "{{ dirs }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - /etc/docker
    - /etc/systemd/system/docker.service.d
  loop_control:
    loop_var: dirs
